### ISSUE TITLE
cant get react box to run

### ISSUE THREAD

**Issue by myptone** [Lapple/react-box#1]
Hi,

I am unable to get react box to run. I downloaded the zip from the git repo and unzipped the code to a folder.

While the compiling and migration worked correctly the line `npm run start` resulted in the following call stack 

```
$ npm run start

> react-box@0.1.0 start C:\node\first_\react-box-master
> node scripts/start.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\node\first_\react-box-master\scripts\start.js:7:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-box@0.1.0 start: `node scripts/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-box@0.1.0 start script 'node scripts/start.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-box package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/start.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-box
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-box
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\node\first_\react-box-master\npm-debug.log

```
No npm-debug.log was generated.

Also I can get the other boxes to run without a problem on the same environment.

Will be grateful for any help :)

Thanks!

**Comment by Lapple** [comment]
Hi, thank you for opening an issue.

Would it help if you run 'npm install' just before running 'npm run start' command? The former should fetch required dependendencies, probably this 'dotenv' package is among them.

Please let me know if it helped.
